myblog/models/post.py
from datetime import datetime
from myblog import db

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    title = db.Column(db.String(100))
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)

    author = db.relationship('User', backref=db.backref('posts', lazy=True))

    def __init__(self, author_id, title, body) -> None:
        self.author_id = author_id
        self.title = title
        self.body = body

    def __repr__(self) -> str:
        return f'Post: {self.title}'

myblog/models/user.py
from myblog import db

class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    password = db.Column(db.String(100))  # Cambio en el tipo de columna para la contraseña

    def __init__(self, username, password) -> None:
        self.username = username
        self.password = password

    def __repr__(self) -> str:
        return f'User: {self.username}'

app.py
from myblog import app

if __name__ == '__main__':
    app.run()

myblog/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)

# Cargar las configuraciones
app.config.from_object('config.DevelopmentConfig')

# Inicializar la base de datos
db = SQLAlchemy(app)

# Importar vistas
from myblog.views.auth import auth
app.register_blueprint(auth)

from myblog.views.blog import blog
app.register_blueprint(blog)

# Crear todas las tablas dentro del contexto de la aplicación
with app.app_context():
    db.create_all()

myblog/views/auth.py
import functools
from os import error
from flask import(
    render_template, Blueprint, flash, g, redirect, request, session, url_for
)

from werkzeug.security import check_password_hash, generate_password_hash

from myblog.models.user import User

from myblog import db

auth = Blueprint('auth', __name__, url_prefix='/auth')

#Registrar un usuario 
@auth.route('/register', methods=('GET','POST'))
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        user = User(username, generate_password_hash(password))

        error = None
        if not username:
            error = 'Se requiere nombre de usuario'
        elif not password:
            error = 'Se requiere contraseña'
        
        user_name = User.query.filter_by(username = username).first()
        if user_name == None:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))
        else:
            error = f'El usuario {username} ya esta registrado'
        flash(error)
        
    return render_template('auth/register.html')

#Iniciar Sesión
@auth.route('/login', methods=('GET','POST'))
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')

        error = None
        
        user = User.query.filter_by(username = username).first()

        if user == None:
            error = 'Datos incorrecto'
        elif not check_password_hash(user.password, password):
            error = 'Datos incorrecto'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('blog.index'))
        
        flash(error)
        
    return render_template('auth/login.html')


@auth.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get_or_404(user_id)

@auth.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('blog.index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

myblog/views/blog.py
from operator import pos
from flask import(
    render_template, Blueprint, flash, g, redirect, request, url_for
)
from markupsafe import Markup
from werkzeug.exceptions import abort

from myblog.models.post import Post
from myblog.models.user import User

from myblog.views.auth import login_required

from myblog import db
blog = Blueprint('blog', __name__)

#Obtner un ususario
def get_user(id):
    user = User.query.get_or_404(id)
    return user

@blog.route("/")
def index():
    posts = Post.query.all()
    posts = list(reversed(posts))
    # Filtrar y marcar como seguro el contenido HTML de cada publicación
    for post in posts:
        post.body = Markup(post.body)

    db.session.commit()
    return render_template('blog/index.html', posts = posts, get_user=get_user)

#Registrar un post 
@blog.route('/blog/create', methods=('GET','POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form.get('title')
        body = request.form.get('body')

        post = Post(g.user.id, title, body)

        error = None
        if not title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        
        flash(error)
        
    return render_template('blog/create.html')

def get_post(id, check_author=True):
    post = Post.query.get(id)

    if post is None:
        abort(404, f'Id {id} de la publicación no existe.')

    if check_author and post.author != g.user.id:
        abort(404)
    
    return post

#Update post 
@blog.route('/blog/update/<int:id>', methods=('GET','POST'))
@login_required
def update(id):

    post = get_post(id) 

    if request.method == 'POST':
        post.title = request.form.get('title')
        post.body = request.form.get('body')

        error = None
        if not post.title:
            error = 'Se requiere un título'
        
        if error is not None:
            flash(error)
        else:
            db.session.add(post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        
        flash(error)
        
    return render_template('blog/update.html', post=post)

#Eliminar un post
@blog.route('/blog/delete/<int:id>')
@login_required
def delete(id):
    post = get_post(id)
    db.session.delete(post)
    db.session.commit()

    return redirect(url_for('blog.index'))

#PERFIL DEL USUARIO
@blog.route('/profile/<int:id>')
def profile(id):
    user_id = get_user(id)
    posts = Post.query.filter_by(author=id).all()
    posts = list(reversed(posts))
    for post in posts:
        post.body = Markup(post.body)

    db.session.commit()
    return render_template('blog/profile.html', posts=posts, get_user=get_user, user_id=user_id)

myblog/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/blog.ico') }}" type="image/x-icon">
    <title>Mi blog | {% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <header class="header">
        <div class="nav">
            <div>
                <a href="{{ url_for('blog.index') }}">
                    <h1>Mi Blog</h1>
                </a>
            </div>
            <nav class="nav-header">
                {% if g.user %}
                {% if request.endpoint == 'blog.profile' %}
                <a href="{{ url_for('blog.create') }}" class="button button-publicar">Publicar algo</a>
                {% endif %}
                <img src="{{ url_for('static', filename='img/user.png') }}" alt="User Icon" class="user-icon">
                <a href="{{ url_for('blog.profile', id=g.user.id) }}" class="user-name">{{ g.user.username }}</a>
                <a href="{{ url_for('auth.logout') }}">Cerrar Sesión</a>
                {% else %}
                    <a href="{{ url_for('auth.register') }}">Registrar Usuario</a>
                    <a href="{{ url_for('auth.login') }}">Iniciar sesión</a>
                {% endif %}
            </nav>
        </div>
    </header>

    <main class="main-content">
        <div class="content">
            <header>{% block header %}{% endblock %}</header>
            {% for message in get_flashed_messages() %}
            <div class="flash-message">
                {{ message }}
            </div>
            {% endfor %}
            {% block content %}{% endblock %}
        </div>
    </main>
    
</body>
</html>

myblog/templates/blog/create.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Crear publicación {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST">
        <label for="title">Título:</label>
        <input type="text" name="title" id="title" placeholder="Escriba el título" required>
        <label for="body">Contenido:</label>
        <textarea name="body" id="body" cols="30" rows="10"></textarea>
        <input type="submit" value="Publicar">
    </form>
    <!-- Agregar CKEditor -->
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/translations/es.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#body'), {
                language: 'es',
                toolbar: {
                    items: [
                        'heading',
                        '|',
                        'bold',
                        'italic',
                        'underline',
                        'strikethrough',
                        '|',
                        'numberedList',
                        'bulletedList',
                        '|',
                        '|',
                        'link',
                        'insertTable',
                        'blockQuote',
                        '|',
                        'undo',
                        'redo'
                    ]
                }
            })
            .catch(error => {
                console.error(error);
            });
    </script>
{% endblock %}

myblog/templates/blog/index.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Publicaciones {% endblock %}</h2>
    {% if g.user %}
        <a href="{{ url_for('blog.create') }}" class="button">Publicar algo</a>
    {% endif %}
{% endblock %}

{% block content %}
    {% for post in posts %}   
        <article class="post">
            <header>
                <div>
                    <h3 class="titulo-post">{{ post.title }}</h3>
                </div>

            </header>
            <div class="post-content ckeditor">
                {{ post.body | safe }}
                <hr>
                <div class="post-meta">
                    Fecha: {{ post.created.strftime('%d-%m-%Y') }}
                    <a href="{{ url_for('blog.profile', id=post.author) }}" class="author-link">Autor: {{ get_user(post.author).username }}</a>
                    <div class="post-actions">
                        {% if g.user.id == post.author %}
                        <a href="{{ url_for('blog.delete', id=post.id) }}" class="button">Eliminar</a>
                        <a href="{{ url_for('blog.update', id=post.id) }}" class="button">Editar</a>
                        {% endif %}
                    </div>
                </div>
                <hr>
            </div>
        </article>
    {% endfor %}
{% endblock %}
<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create(document.querySelector('.ckeditor'))
        .catch(error => {
            console.error(error);
        });
</script>

myblog/templates/blog/profile.html
{% extends 'base.html' %}

{% block header %}
    <div class="profile-header">
        <img src="{{ url_for('static', filename='img/user.png') }}" alt="User Icon" class="user-icon">
        <h2>{% block title %}Perfil de {{ user_id.username }} {% endblock %}</h2>
    </div>
{% endblock %}

{% block content %}
<h1>Todas las publicaciones</h1>
{% for post in posts %}   
<article class="post">
    <header>
        <h3 class="titulo-post">{{ post.title }}</h3>
    </header>
    <div class="post-content">
        <p>{{ post.body | safe }}</p>
    </div>
    <div class="post-meta">
        <a href="{{ url_for('blog.profile', id=post.author) }}" class="author-link">Autor: {{ get_user(post.author).username }}</a>
        Fecha: {{ post.created.strftime('%d-%m-%Y') }}
        <div class="post-actions">
            {% if g.user.id == post.author %}
            <a href="{{ url_for('blog.delete', id=post.id) }}" class="button">Eliminar</a>
            <a href="{{ url_for('blog.update', id=post.id) }}" class="button">Editar</a>
            {% endif %}
        </div>
    </div>
</article>
{% endfor %}
{% endblock %}
<script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
<script>
    ClassicEditor
        .create(document.querySelector('.ckeditor'))
        .catch(error => {
            console.error(error);
        });
</script>

myblog/templates/blog/update.html
{% extends 'base.html' %}
{% block header %}
    <h2>{% block title %}Actualizar una publicación {% endblock %}</h2>
{% endblock %}

{% block content %}
    <form method="POST">
        <label for="title">Título</label>
        <input type="text" name="title" id="title" value="{{ post.title }}" required>
        <label for="body">Contenido</label>
        <textarea name="body" id="body" cols="30" rows="10">{{ post.body | safe }}</textarea>
        <input type="submit", value="Editar">
    </form>
    <!-- Agregar CKEditor -->
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/ckeditor.js"></script>
    <script src="https://cdn.ckeditor.com/ckeditor5/41.4.2/classic/translations/es.js"></script>
    <script>
        ClassicEditor
            .create(document.querySelector('#body'), {
                language: 'es',
                toolbar: {
                    items: [
                        'heading',
                        '|',
                        'bold',
                        'italic',
                        'underline',
                        'strikethrough',
                        '|',
                        'numberedList',
                        'bulletedList',
                        '|',
                        '|',
                        'link',
                        'insertTable',
                        'blockQuote',
                        '|',
                        'undo',
                        'redo'
                    ]
                }
            })
            .catch(error => {
                console.error(error);
            });
    </script>
{% endblock %}